### ISSUE TITLE
It does not work on the 6.12 kernel

### ISSUE THREAD

**Issue by Podberezovik34** [Kyuunex/hid-sony-clone-fix-dkms#5]
It does not work on the 6.12 kernel, the person showed the problem using this link.

 https://github.com/ozz-is-here/hid-sony-fix-dkms/issues/1

**Comment by qnxt** [comment]
From README:

## Not needed since kernel 6.2
Since kernel `6.2`, a new `hid-playstation` driver is included in the kernel 
which seems to work with controlers that do not support HID feature report 0x81, 
and thus, this patch is no longer needed.  

There is nothing to do here. This patch is unsupported since 6.2. 
I plugged in the controller in question while running 6.12 and it works just fine, without this patch.
